# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8b0f8f3dfdbf7228b39e2c67f90c9612"
name = "July-App"
handle = "july-app-2"
application_url = "https://memory-picture-tuning-cz.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://memory-picture-tuning-cz.trycloudflare.com/auth/callback",
  "https://memory-picture-tuning-cz.trycloudflare.com/auth/shopify/callback",
  "https://memory-picture-tuning-cz.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
